lab 4-5
Osipchik/FrontEnd_tasks pull request #4
Opened 2021-06-02 19:46 UTC by Osipchik

[deploy link](https://spa-app-fa4b0.firebaseapp.com/)

I had some problems with deploying the application, so I created a [second repository](https://github.com/Tim-Osipchik/spa) with this project, everything worked out there.

Tthe code in both repositories is the same

2021-06-03 17:39 UTC, gmltA requested changes
Can you publish your changes so I can see not the whole code, but the difference somehow?

2021-06-03 17:39 UTC, gmltA commented
Also the music is not playing for me...

2021-06-03 22:14 UTC, Osipchik commented
I've added the music player and removed the folder with styles they are the same as in the previous pr

2021-06-04 11:57 UTC, gmltA approved these changes
Looks solid.

That's an overall <kbd>9</kbd>.

Good luck!

2021-06-04 11:57 UTC, gmltA commented on public/utils/componentsHelper.js
> +    }
👍

2022-11-17 23:20 UTC, closed without merging